### ISSUE TITLE
NotImplementedError: cannot instantiate 'WindowsPath' on your system

### ISSUE THREAD

**Issue by BenjiKCF** [RCVLab-AiimLab/crowd_counting#3]
I am unable to load the pretrained model. I guess the pretrained model was done on a Windows PC and my system is on Ubuntu.
Is there anyway to convert it to a linux file?

> Model Summary: 116 layers, 21935940 parameters, 21935940 gradients
> Traceback (most recent call last):
>   File "eval.py", line 246, in <module>
>     eval()
>   File "eval.py", line 71, in eval
>     checkpoint = torch.load('/home/cairs/code/crowd/multitask/crowd_counting/runs/weights/ShanghaiA_multi/model_best.pth.tar')
>   File "/home/cairs/miniconda3/envs/multitask/lib/python3.8/site-packages/torch/serialization.py", line 712, in load
>     return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
>   File "/home/cairs/miniconda3/envs/multitask/lib/python3.8/site-packages/torch/serialization.py", line 1049, in _load
>     result = unpickler.load()
>   File "/home/cairs/miniconda3/envs/multitask/lib/python3.8/pathlib.py", line 1043, in __new__
>     raise NotImplementedError("cannot instantiate %r on your system"
> NotImplementedError: cannot instantiate 'WindowsPath' on your system

**Comment by wangrui9** [comment]
Have you solved this problem？i have  this problem,too.
